### ISSUE TITLE
Graphic tooling is not portable

### ISSUE THREAD

**Issue by stopbystudent** [knut-o/nloptwr#4]
The file `misc/test6_grafik.sh` does not follow bash best practices and is not portable (its dependencies are unclear unless inspected manually).

https://github.com/knut-o/nloptwr/blob/f79bf133e29738980136adc90c5cefeec28ed089/misc/test6_grafik.sh#L1

This should use `/usr/bin/env bash` to not rely on `/bin`.

https://github.com/knut-o/nloptwr/blob/f79bf133e29738980136adc90c5cefeec28ed089/misc/test6_grafik.sh#L2

This line does require the presence of a build directory. But that is not always the case. This should be checked beforehand (maybe exiting if the build directory does not exist or alternatively, creating it).

https://github.com/knut-o/nloptwr/blob/f79bf133e29738980136adc90c5cefeec28ed089/misc/test6_grafik.sh#L8

This does require `xpdf` to be installed. That is not necessarily the case. I wonder what was the reason not to use `xdg-open` which would be the usual thing to do on Linux platforms.

Additionally, the script should test if gnuplot is installed at all. Otherwise, processing the file will fail anyway.

**Comment by knut-o** [comment]
The bug is fixed.
